/**
 * Generated server utilities for Convex component.
 * This file provides the action/query/mutation builders used by the component.
 *
 * NOTE: In production, this file is generated by `npx convex dev`.
 * This placeholder enables TypeScript compilation and IDE support.
 */

import type {
	ActionBuilder,
	GenericActionCtx,
	GenericDataModel,
	GenericMutationCtx,
	GenericQueryCtx,
	MutationBuilder,
	QueryBuilder,
} from "convex/server";

// Re-export the function builders with proper types
// These are placeholders that will be replaced by actual generated code
export const action = (() => {}) as unknown as ActionBuilder<
	GenericDataModel,
	"public"
>;
export const internalAction = (() => {}) as unknown as ActionBuilder<
	GenericDataModel,
	"internal"
>;
export const query = (() => {}) as unknown as QueryBuilder<
	GenericDataModel,
	"public"
>;
export const internalQuery = (() => {}) as unknown as QueryBuilder<
	GenericDataModel,
	"internal"
>;
export const mutation = (() => {}) as unknown as MutationBuilder<
	GenericDataModel,
	"public"
>;
export const internalMutation = (() => {}) as unknown as MutationBuilder<
	GenericDataModel,
	"internal"
>;

// Context types
export type ActionCtx = GenericActionCtx<GenericDataModel>;
export type QueryCtx = GenericQueryCtx<GenericDataModel>;
export type MutationCtx = GenericMutationCtx<GenericDataModel>;
